In [4]:
import sys
import numpy as np
import pandas as pd
# from scipy.misc import imread
import pickle
import os
import matplotlib.pyplot as plt
%matplotlib inline

import cv2
import time

import tensorflow as tf
from keras.models import Sequential
from keras.optimizers import Adam
from keras.layers import Conv2D, ZeroPadding2D, Activation, Input, concatenate
from keras.models import Model

from PIL import Image

from keras.layers.normalization import BatchNormalization
from keras.layers.pooling import MaxPooling2D
from keras.layers.merge import Concatenate
from keras.layers.core import Lambda, Flatten, Dense
from keras.initializers import glorot_uniform

from keras.engine.topology import Layer
from keras.regularizers import l2
from keras import backend as K

from tqdm import tqdm

from sklearn.utils import shuffle

import numpy as np
import shapely.wkt
import shapely
from shapely.geometry import Polygon

In [5]:
def initialize_weights(shape, name=None):
    """
        The paper, http://www.cs.utoronto.ca/~gkoch/files/msc-thesis.pdf
        suggests to initialize CNN layer weights with mean as 0.0 and standard deviation of 0.01
    """
    return np.random.normal(loc = 0.0, scale = 1e-2, size = shape)

In [6]:

def initialize_bias(shape, name=None):
    """
        The paper, http://www.cs.utoronto.ca/~gkoch/files/msc-thesis.pdf
        suggests to initialize CNN layer bias with mean as 0.5 and standard deviation of 0.01
    """
    return np.random.normal(loc = 0.5, scale = 1e-2, size = shape)

In [7]:
# https://medium.com/@prabhnoor0212/siamese-network-keras-31a3a8f37d04
def get_siamese_model(input_shape):
    """
        Model architecture based on the one provided in: http://www.cs.utoronto.ca/~gkoch/files/msc-thesis.pdf
    """
    
    # Define the tensors for the two input images
    left_input = Input(input_shape)
    right_input = Input(input_shape)
    
    # Convolutional Neural Network
    model = Sequential()
    model.add(Conv2D(16, (10,10), activation='relu', input_shape=input_shape,
                   kernel_initializer='he_normal', kernel_regularizer=l2(2e-3)))
    model.add(MaxPooling2D())
    model.add(Conv2D(32, (7,7), activation='relu',
                     kernel_initializer='he_normal',
                     bias_initializer='he_normal', kernel_regularizer=l2(2e-3)))
    model.add(MaxPooling2D())
    model.add(Conv2D(64, (4,4), activation='relu', kernel_initializer='he_normal',
                     bias_initializer='he_normal', kernel_regularizer=l2(2e-3)))
    model.add(MaxPooling2D())
#     model.add(Conv2D(128, (4,4), activation='relu', kernel_initializer='he_normal',
#                      bias_initializer='he_normal', kernel_regularizer=l2(2e-4)))
    model.add(Flatten())
    model.add(Dense(4096, activation='sigmoid',
                   kernel_regularizer=l2(1e-3),
                   kernel_initializer='he_normal',bias_initializer='he_normal'))
    
    # Generate the encodings (feature vectors) for the two images
    encoded_l = model(left_input)
    encoded_r = model(right_input)
    
    # Add a customized layer to compute the absolute difference between the encodings
    L1_layer = Lambda(lambda tensors:K.abs(tensors[0] - tensors[1]))
    L1_distance = L1_layer([encoded_l, encoded_r])
    
    # Add a dense layer with a sigmoid unit to generate the similarity score
    prediction = Dense(1,activation='sigmoid',bias_initializer='he_normal')(L1_distance)
    
    # Connect the inputs with the outputs
    siamese_net = Model(inputs=[left_input,right_input],outputs=prediction)
    
    # return the model
    return siamese_net

In [8]:
model = get_siamese_model((224, 224, 3))

optimizer = Adam(lr = 0.00001)
model.compile(loss="binary_crossentropy",optimizer=optimizer)

model.summary()


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
sequential_1 (Sequential)       (None, 4096)         138741040   input_1[0][0]                    
                                                                 input_2[0][0]                    
________________________________________________________________________________________________

In [9]:
with open('/home/abhirag/experiments_on_portugal/training_data.pkl', 'rb') as fp:
    training_data = pickle.load(fp)

In [10]:
count_no_damage = 0
count_of_destroyed = 0 
data_for_siamese_training = []
for img_name in list(training_data.keys()):
    for uid in list(training_data[img_name].keys()):
        if training_data[img_name][uid]['label'] != 'un-classified':
            if training_data[img_name][uid]['label'] == 'no-damage' and count_no_damage < 250:
                
#                 print(img_name)
#                 print(uid)
                
                
                pre_img = np.array(Image.fromarray(training_data[img_name][uid]['pre']).resize((224, 224))).reshape(224, 224, 3)
                post_img = np.array(Image.fromarray(training_data[img_name][uid]['post']).resize((224, 224))).reshape(224, 224, 3)
                count_no_damage += 1
                data_for_siamese_training.append(([pre_img, post_img], [0], [training_data[img_name][uid]['label']]))
                #model.fit([pre_img, post_img], [0])
            elif training_data[img_name][uid]['label'] != 'no-damage':
                if training_data[img_name][uid]['label'] == 'destroyed' and count_of_destroyed < 250:
                    
                    pre_img = np.array(Image.fromarray(training_data[img_name][uid]['pre']).resize((224, 224))).reshape(224, 224, 3)
                    post_img = np.array(Image.fromarray(training_data[img_name][uid]['post']).resize((224, 224))).reshape(224, 224, 3)
                    data_for_siamese_training.append(([pre_img, post_img], [1],[training_data[img_name][uid]['label']]))
                    count_of_destroyed += 1
                elif training_data[img_name][uid]['label'] != 'destroyed' :
                    pre_img = np.array(Image.fromarray(training_data[img_name][uid]['pre']).resize((224, 224))).reshape(224, 224, 3)
                    post_img = np.array(Image.fromarray(training_data[img_name][uid]['post']).resize((224, 224))).reshape(224, 224, 3)
                    data_for_siamese_training.append(([pre_img, post_img], [1],[training_data[img_name][uid]['label']]))

                    #model.fit([pre_img, post_img], [1])
#         break
#     break

In [11]:
print(len(data_for_siamese_training))


875


In [9]:
damage = [d[2][0] for d in data_for_siamese_training]
#print(damage)
for i in set(damage):
    print('counts of ', i, ' = ', damage.count(i))

counts of  no-damage  =  250
counts of  destroyed  =  250
counts of  major-damage  =  231
counts of  minor-damage  =  144


In [10]:
import random
from tqdm import tqdm
batch_size = 32
epochs = 50 
no_of_batches = int(len(data_for_siamese_training) / batch_size)

def get_batch_data(data_for_siamese_training, index):
    random.shuffle(data_for_siamese_training)
    inp = []
    target = []
    pre_data = []
    post_data = []
    for i in range(index* batch_size, (index+1) * batch_size):
        pre_data.append(np.array(data_for_siamese_training[i][0][0]))
        post_data.append(np.array(data_for_siamese_training[i][0][1]))

        #inp.append([np.array(data_for_siamese_training[i][0][0]), np.array(data_for_siamese_training[i][0][1])])
        #inp.append(data_for_siamese_training[i][0])
        target.append(data_for_siamese_training[i][1][0])

    inp.append(pre_data) 
    inp.append(post_data)
    
    return inp,target

    
for i in range(epochs):
    total_loss = 0
    for j in range(no_of_batches) :
        inp, target = get_batch_data(data_for_siamese_training, j)
        loss = model.train_on_batch(inp,target)
        preds = model.predict_on_batch(inp)
        #print(preds)
        #preds = [1 if pred > 0.5 else 0 for pred in preds]
        #print(preds)
        
        total_loss += loss
        
    print("for epoch : ", i, " loss is : ", total_loss/no_of_batches)



for epoch :  0  loss is :  9.012404335869682
for epoch :  1  loss is :  8.658326360914442
for epoch :  2  loss is :  8.437366061740452
for epoch :  3  loss is :  8.161467693470142
for epoch :  4  loss is :  7.934523140942609
for epoch :  5  loss is :  7.688010798560248
for epoch :  6  loss is :  7.47329655400029
for epoch :  7  loss is :  7.242268350389269
for epoch :  8  loss is :  7.023373462535717
for epoch :  9  loss is :  6.8199291759067115
for epoch :  10  loss is :  6.656363787474455
for epoch :  11  loss is :  6.462194425088388
for epoch :  12  loss is :  6.2926425227412475
for epoch :  13  loss is :  6.129975831067121
for epoch :  14  loss is :  5.987438978972258
for epoch :  15  loss is :  5.856455273098415
for epoch :  16  loss is :  5.727321783701579
for epoch :  17  loss is :  5.613326302281132
for epoch :  18  loss is :  5.496279257315177
for epoch :  19  loss is :  5.367311742570665
for epoch :  20  loss is :  5.265688648930302
for epoch :  21  loss is :  5.181750915668

In [11]:
preds_model = []
lables = []
damage_lables = []
for i in range(len(data_for_siamese_training)):
    aa = []
    aa.append(np.array(data_for_siamese_training[i][0][0]).reshape(1, 224, 224, 3))
    aa.append(np.array(data_for_siamese_training[i][0][1]).reshape(1, 224, 224, 3))

    preds_model.append(model.predict(aa))
    lables.append(data_for_siamese_training[i][1][0])
    damage_lables.append(data_for_siamese_training[i][2][0])
    

In [12]:
preds = [1 if pred > 0.5 else 0 for pred in preds_model]
correct_count = 0
for i in range(len(preds)):
    if preds[i] == lables[i]:
        correct_count += 1
        
print("siamese damage Vs no damage accuracy : ", correct_count/ len(preds) *100)

siamese damage Vs no damage accuracy :  91.77142857142857


In [13]:
preds_model

[array([[0.96743697]], dtype=float32),
 array([[0.91662467]], dtype=float32),
 array([[0.9409592]], dtype=float32),
 array([[0.9335786]], dtype=float32),
 array([[0.9937995]], dtype=float32),
 array([[0.3483474]], dtype=float32),
 array([[0.99768794]], dtype=float32),
 array([[0.7624104]], dtype=float32),
 array([[0.934306]], dtype=float32),
 array([[0.88608646]], dtype=float32),
 array([[0.24677666]], dtype=float32),
 array([[0.9806126]], dtype=float32),
 array([[0.7504544]], dtype=float32),
 array([[0.98084027]], dtype=float32),
 array([[0.63775146]], dtype=float32),
 array([[0.20708853]], dtype=float32),
 array([[0.27294463]], dtype=float32),
 array([[0.97527516]], dtype=float32),
 array([[0.9709145]], dtype=float32),
 array([[0.8227908]], dtype=float32),
 array([[0.950511]], dtype=float32),
 array([[0.93123806]], dtype=float32),
 array([[0.9050821]], dtype=float32),
 array([[0.8290488]], dtype=float32),
 array([[0.5977251]], dtype=float32),
 array([[0.21898054]], dtype=float32),
 a

In [14]:
pred_4_class = []
for pred in preds_model :
    if pred < 0.4 :
        pred_4_class.append('0')
    elif pred < 0.6 :
        pred_4_class.append('1')
    elif pred < 0.8 :
        pred_4_class.append('2')
    else :
        pred_4_class.append('3')

damage_mappings = {'no-damage' : '0', 'minor-damage' : '1', 'major-damage' : '2', 'destroyed': '3'}
damage_gt = [damage_mappings.get(item) for item in damage_lables]
print(len(damage_gt))
print(len(pred_4_class))
correct_count = 0
for i in range(len(pred_4_class)):
    if pred_4_class[i] == damage_gt[i]:
        correct_count += 1
        
print("accuracy : ", correct_count/ len(pred_4_class) *100)

875
875
accuracy :  52.68571428571428


In [15]:
preds

[1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_pred = pred_4_class, y_true = damage_gt))


              precision    recall  f1-score   support

           0       0.90      0.78      0.84       250
           1       0.22      0.09      0.13       144
           2       0.35      0.16      0.22       231
           3       0.44      0.86      0.58       250

    accuracy                           0.53       875
   macro avg       0.48      0.47      0.44       875
weighted avg       0.51      0.53      0.48       875



In [17]:
model.save("siamese_classification.h5")

In [12]:
from keras.models import load_model

model = load_model('siamese_classification.h5')



In [13]:


import json, os, random
from PIL import Image


def process_img(img_array, polygon_pts, scale_pct):
    height, width, _ = img_array.shape

    xcoords = polygon_pts[:, 0]
    ycoords = polygon_pts[:, 1]
    xmin, xmax = np.min(xcoords), np.max(xcoords)
    ymin, ymax = np.min(ycoords), np.max(ycoords)

    xdiff = xmax - xmin
    ydiff = ymax - ymin

    #Extend image by scale percentage
#     xmin = max(int(xmin - (xdiff * scale_pct)), 0)
#     xmax = min(int(xmax + (xdiff * scale_pct)), width)
#     ymin = max(int(ymin - (ydiff * scale_pct)), 0)
#     ymax = min(int(ymax + (ydiff * scale_pct)), height)

    return img_array[int(ymin):int(ymax), int(xmin):int(xmax), :]

base = '/home/abhirag/ONLY_PORTUGAL/validation/'

images_list = [base + i for i in os.listdir(base)]

random.shuffle(images_list)

predicted_labels = []
actual_labels = []
################################################################################################



for i in images_list:
    
#     i = '/home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001119_post_disaster.png'
    
    if i.split('_')[3] == 'post' and i.split('.')[-1] == 'png':

        
        
        print('PROCESSING +++++++ ', i)
        post_image_to_process = i
        pre_image_to_process = i.replace('_post_', '_pre_')

        pre_img_arr = np.array(Image.open(pre_image_to_process))
        post_img_arr = np.array(Image.open(post_image_to_process))

        # PROCESS THE ABOVE IMAGE USING SPACENET INFERENCE AND GET OUTPUT JSON

        os.system('python3 /home/abhirag/experiments_on_portugal/spacenet/src/models/inference.py --input ' + i + ' --weights /home/abhirag/experiments_on_portugal/spacenet/models/logs/model_iter_711 --mean /home/abhirag/experiments_on_portugal/spacenet_gt/dataSet/mean.npy --output /home/abhirag/experiments_on_portugal/output_json.json')


        data = json.load(open('/home/abhirag/experiments_on_portugal/output_json.json'))



        # POLYGON IS IN HERE == data['features']['xy'][0]['wkt']

        # OUTPUT OF ABOVE COMMAND IS 'POLYGON ((645.0 944.0,645.0 945.0,643.0 947.0,645.0 947.0,645.0 944.0))'

        # polygon_pts IS OUTPUT POLYGON FROM SEGMENTATION MODEl

        # WILL HAVE TO ITERATE OVER ALL POLYGONS IN TRAINING JSON TO CALCULATE MAX IOU OVER ALL POLYGONS

        original_json = json.load(open(post_image_to_process.replace('png', 'json')))

        # THIS DICTIONARY IS OF THE FORM {'uid' : {'IOU' : some percentage, 'damage' : level_of_damage}}

        max_ious = {}

        
        
        
        
        
        for x in range(len(data['features']['xy'])):
            max_ious[data['features']['xy'][x]['properties']['uid']] = {'max' : 0, 'damage' : None}
            polygon_geom = shapely.wkt.loads(data['features']['xy'][x]['wkt'])

            max = 0
            d = None

            for i in range(len(original_json['features']['xy'])):
                polygon_original = shapely.wkt.loads(original_json['features']['xy'][i]['wkt'])
                try:
                    if polygon_geom.intersection(polygon_original):
                        iou = polygon_geom.intersection(polygon_original).area / polygon_geom.union(polygon_original).area
                        if iou > max:
                            max = iou
                            d = original_json['features']['xy'][i]['properties']['subtype']
                        # print(iou)
                except:
                    pass

            if max == 0:
                del max_ious[data['features']['xy'][x]['properties']['uid']]
            else:
                max_ious[data['features']['xy'][x]['properties']['uid']]['max'] = max
                max_ious[data['features']['xy'][x]['properties']['uid']]['damage'] = d

#         print(max_ious)
        
        list_of_polygons = list(max_ious.keys())


        for i in range(len(data['features']['xy'])):
            if data['features']['xy'][i]['properties']['uid'] in list_of_polygons:
                
                actual_labels.append(max_ious[data['features']['xy'][i]['properties']['uid']]['damage'])

                poly = np.array(list(shapely.wkt.loads(data['features']['xy'][i]['wkt']).exterior.coords))

                pre_x = process_img(pre_img_arr, poly, 1.0)
                post_x = process_img(post_img_arr, poly, 1.0)

        #         print('pre = ', pre_x.shape)
        #         print('post = ', post_x.shape)

                pre = np.array(Image.fromarray(pre_x, 'RGB').resize((224, 224))).reshape(1, 224, 224, 3)
                post = np.array(Image.fromarray(post_x, 'RGB').resize((224, 224))).reshape(1, 224, 224, 3)
                
                predicted_labels.append(model.predict([pre, post]))
                
            
#     break

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001626_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 812 at 131 812
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 812 at 131 812
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 812 at 131 812


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001051_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001104_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001121_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000583_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001321_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 198 596 at 198 596


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000612_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 9 935 at 9 935
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 3 912 at 3 912
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 3 912 at 3 912
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 3 906 at 3 906
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 33 815 at 33 815
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 21 760 at 21 760


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001099_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000500_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001678_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000326_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001019_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 757 896 at 757 896
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 662 824 at 662 824
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 662 824 at 662 824
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 742 304 at 742 304
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 791 124 at 791 124
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 865 67 at 865 67
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 865 67 at 865 67
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 865 67 at 865 67
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 955 34 at 955 34
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 769 32 at 769 32


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000840_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000955_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001514_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000992_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000161_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 465 929 at 465 929
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 813 891 at 813 891
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 142 100 at 142 100
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 856 63 at 856 63
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 18 53 at 18 53


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001211_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001353_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001573_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001608_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000036_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000110_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 451 739 at 451 739
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 122 658 at 122 658
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 106 658 at 106 658
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 251 284 at 251 284
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 251 284 at 251 284


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001659_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 865 856 at 865 856


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000108_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001062_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001138_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001828_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001589_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001200_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000553_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000301_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001757_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 473 422 at 473 422


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001059_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 723 230 at 723 230


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000194_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001760_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000829_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001299_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001339_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 564 325 at 564 325


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001499_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000542_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000381_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000436_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 768 82 at 768 82
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 160 27 at 160 27


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001680_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001568_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 634 195 at 634 195


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000121_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000914_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 56 788 at 56 788
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 864 364 at 864 364
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 15 276 at 15 276


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001714_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001039_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000347_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000049_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000831_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000721_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000168_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000282_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001612_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 229 874 at 229 874


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000884_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000591_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000837_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000107_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001415_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001381_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001056_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001072_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000818_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 461 264 at 461 264
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 745 48 at 745 48


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000165_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000369_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000196_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001313_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 687 485 at 687 485


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000104_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000898_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 989 502 at 989 502
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 259 52 at 259 52


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000499_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001390_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000319_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001348_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001179_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000729_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001581_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001480_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001073_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 616 975 at 616 975
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 123 894 at 123 894
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 111 746 at 111 746
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1020 431 at 1020 431
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 996 400 at 996 400
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 872 312 at 872 312
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 36 268 at 36 268
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 860 262 at 860 262
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 860 262 at 860 262
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 860 262 at 860 262
TopologyException: I

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001780_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000300_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000376_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001309_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001533_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000962_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001050_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000617_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001209_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 227 311 at 227 311
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 98 264 at 98 264
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 171 242 at 171 242
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 316 225 at 316 225
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 316 225 at 316 225
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 481 213 at 481 213
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 93 215 at 93 215
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 93 215 at 93 215
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 93 215 at 93 215
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 484 108 at 484 108
TopologyException:

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001738_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000487_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000550_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001463_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001347_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001751_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000207_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000147_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001842_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 995 at 910 995
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 722 628 at 722 628
TopologyExcepti

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000056_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 584 983 at 584 983
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 544 924 at 544 924
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 699 808 at 699 808
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 429 734 at 429 734
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 431 728 at 431 728
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 300 595 at 300 595


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001808_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 101 315 at 101 315
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 101 315 at 101 315


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000838_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000535_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 320 845 at 320 845
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 512 647 at 512 647
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 175 600 at 175 600
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1013 592 at 1013 592
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 367 30 at 367 30
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 360 31 at 360 31
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 357 18 at 357 18


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000292_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001137_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001124_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001332_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000038_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001781_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000213_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 120 146 at 120 146
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 54 114 at 54 114
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 54 114 at 54 114
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 54 114 at 54 114


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001851_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001576_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001569_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000403_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001862_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001165_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000072_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000064_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001237_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 608 906 at 608 906
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 2 369 at 2 369


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001440_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 295 876 at 295 876
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 295 876 at 295 876
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 19 720 at 19 720
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 197 455 at 197 455
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 240 428 at 240 428
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 144 426 at 144 426
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 144 426 at 144 426
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 144 426 at 144 426
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 144 426 at 144 426
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 144 426 at 144 426
TopologyException: Inp

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001655_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 5 851 at 5 851
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 32 833 at 32 833
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 32 833 at 32 833
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 32 833 at 32 833
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 32 833 at 32 833
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 277 654 at 277 654


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000883_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000085_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000844_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001249_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001544_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 663 970 at 663 970
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 333 923 at 333 923
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 330 920 at 330 920
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 456 896 at 456 896
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 444 710 at 444 710


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001460_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001162_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000603_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001664_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 690 370 at 690 370
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 507 127 at 507 127


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000592_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 380 957 at 380 957
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 380 957 at 380 957
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 766 825 at 766 825
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 848 633 at 848 633
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 636 621 at 636 621
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 636 621 at 636 621
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 636 621 at 636 621
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 860 611 at 860 611
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 359 181 at 359 181


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000894_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000151_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000159_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 383 337 at 383 337


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000025_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001817_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 601 233 at 601 233


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000150_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001725_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 256 1002 at 256 1002


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001774_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000774_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001843_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001743_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 172 894 at 172 894
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 633 796 at 633 796
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 633 796 at 633 796
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 639 787 at 639 787
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 455 713 at 455 713
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 398 717 at 398 717
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 398 717 at 398 717
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 442 710 at 442 710


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001428_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000174_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000226_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 437 407 at 437 407
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 437 407 at 437 407
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 426 394 at 426 394
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 469 287 at 469 287
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 472 280 at 472 280
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 470 278 at 470 278
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 469 94 at 469 94
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 476 89 at 476 89
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 513 78 at 513 78


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000010_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001809_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000350_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001256_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001787_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 974 164 at 974 164
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 974 164 at 974 164
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 817 101 at 817 101
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 814 101 at 814 101
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 540 11 at 540 11
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 540 11 at 540 11
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 535 8 at 535 8
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 535 8 at 535 8


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000935_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000338_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000720_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 598 1012 at 598 1012
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 921 837 at 921 837
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 921 837 at 921 837
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 804 590 at 804 590


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001766_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 23 952 at 23 952
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 877 889 at 877 889
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 550 893 at 550 893
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 879 866 at 879 866
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 509 862 at 509 862
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 509 862 at 509 862
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 823 788 at 823 788
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 441 514 at 441 514
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 441 514 at 441 514
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 441 514 at 441 514


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000486_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 772 771 at 772 771
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 772 771 at 772 771
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 819 748 at 819 748


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000126_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000258_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000687_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001259_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 705 683 at 705 683
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 705 683 at 705 683
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 656 545 at 656 545
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 656 541 at 656 541
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 656 541 at 656 541
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 656 541 at 656 541


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001666_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001187_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 414 164 at 414 164
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 414 164 at 414 164


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001054_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001319_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 990 388 at 990 388
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 990 388 at 990 388


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000184_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001850_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001206_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001100_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000548_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000067_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000122_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001011_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001674_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 995 235 at 995 235


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001430_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000599_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 560 483 at 560 483
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 16 187 at 16 187


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001833_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000305_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000299_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001277_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001622_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000392_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001163_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000722_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000804_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 2 37 at 2 37


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001401_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001359_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000274_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 963 825 at 963 825
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 480 65 at 480 65


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000485_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000045_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000203_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001283_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001221_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000994_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001367_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000318_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001082_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 975 1021 at 975 1021
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 975 1021 at 975 1021
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 814 905 at 814 905


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000231_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001478_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000696_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000371_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 296 193 at 296 193


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001534_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000391_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001541_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000123_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 155 405 at 155 405
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 396 24 at 396 24


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001696_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000565_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001665_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000946_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000793_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000834_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 261 169 at 261 169


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000268_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000859_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001802_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000596_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000821_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001055_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000433_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 813 878 at 813 878
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 689 875 at 689 875


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000379_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000441_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001127_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001030_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000510_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001594_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000662_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000461_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001226_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 15 376 at 15 376
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 319 326 at 319 326
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 319 326 at 319 326
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 17 337 at 17 337
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 377 302 at 377 302
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 377 302 at 377 302
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 283 118 at 283 118


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000431_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000877_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001502_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000348_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001442_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000378_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000784_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 10 338 at 10 338
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 212 91 at 212 91
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 348 82 at 348 82
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 402 20 at 402 20
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 116 18 at 116 18


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000595_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001495_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000520_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000968_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000524_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000679_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 338 322 at 338 322
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 886 292 at 886 292


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001323_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 755 583 at 755 583
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 868 510 at 868 510
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 829 475 at 829 475


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000426_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001134_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000506_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001424_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000965_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 878 302 at 878 302


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000352_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001293_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000574_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001166_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 979 134 at 979 134
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 858 106 at 858 106


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001829_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000193_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 32 397 at 32 397


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000438_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000727_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000112_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001762_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001427_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001422_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 540 805 at 540 805
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 569 796 at 569 796
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 569 796 at 569 796
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 541 787 at 541 787
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 858 55 at 858 55


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001412_post_disaster.png


TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 1021 249 at 1021 249
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1007 243 at 1007 243


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001719_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 390 986 at 390 986
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 484 at 131 484
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 484 at 131 484
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 484 at 131 484
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 131 484 at 131 484
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 689 451 at 689 451


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001584_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001444_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001755_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000735_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000354_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1008 705 at 1008 705
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 938 308 at 938 308
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 942 309 at 942 309
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 2 145 at 2 145
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 2 145 at 2 145
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 981 44 at 981 44


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001329_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001432_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001012_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000363_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001151_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000142_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001177_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001759_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000515_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 901 612 at 901 612
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 901 612 at 901 612
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 898 604 at 898 604
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 898 604 at 898 604
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 879 535 at 879 535
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 879 535 at 879 535


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000409_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000688_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001650_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001175_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000222_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001771_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000988_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000825_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001599_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 140 387 at 140 387
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 178 304 at 178 304
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 178 304 at 178 304
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 178 304 at 178 304
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 91 41 at 91 41
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 91 41 at 91 41
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 91 41 at 91 41


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001368_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000854_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001052_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001358_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000751_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 323 706 at 323 706


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000887_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000236_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001758_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000192_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000117_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001135_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001046_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001486_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000002_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 669 95 at 669 95
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 719 84 at 719 84


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001191_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000006_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 422 340 at 422 340
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 916 213 at 916 213
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 910 170 at 910 170
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 924 94 at 924 94
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 924 94 at 924 94
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 924 94 at 924 94
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 61 34 at 61 34
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 820 24 at 820 24
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 820 24 at 820 24
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 820 24 at 820 24
TopologyException: Input geom 0 is i

PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001453_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000182_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000375_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 984 801 at 984 801
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 984 742 at 984 742


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001304_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001490_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000555_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001784_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001654_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000559_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001330_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001098_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 90 687 at 90 687
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 90 687 at 90 687
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 90 687 at 90 687
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 216 410 at 216 410
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 181 476 at 181 476
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 181 476 at 181 476
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 189 326 at 189 326
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 206 319 at 206 319


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000650_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1021 828 at 1021 828


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001651_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000070_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001619_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001161_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000303_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001813_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000892_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 173 680 at 173 680


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000683_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000933_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000397_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000410_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000140_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000557_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001119_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000695_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001482_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 397 817 at 397 817
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 671 744 at 671 744


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000663_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000119_post_disaster.png


TopologyException: Input geom 0 is invalid: Self-intersection at or near point 871 700 at 871 700


PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000686_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001020_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000526_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001258_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001220_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001180_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000120_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00001868_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portugal-wildfire_00000204_post_disaster.png
PROCESSING +++++++  /home/abhirag/ONLY_PORTUGAL/validation/portu

In [14]:
predicted_labels



[array([[0.22219007]], dtype=float32),
 array([[0.2479168]], dtype=float32),
 array([[0.26922423]], dtype=float32),
 array([[0.33375576]], dtype=float32),
 array([[0.21271667]], dtype=float32),
 array([[0.24157263]], dtype=float32),
 array([[0.2260262]], dtype=float32),
 array([[0.24154387]], dtype=float32),
 array([[0.2002147]], dtype=float32),
 array([[0.22671439]], dtype=float32),
 array([[0.2282411]], dtype=float32),
 array([[0.20288533]], dtype=float32),
 array([[0.19421248]], dtype=float32),
 array([[0.21124016]], dtype=float32),
 array([[0.21683383]], dtype=float32),
 array([[0.71866214]], dtype=float32),
 array([[0.20201503]], dtype=float32),
 array([[0.29308653]], dtype=float32),
 array([[0.2297414]], dtype=float32),
 array([[0.22445263]], dtype=float32),
 array([[0.18724991]], dtype=float32),
 array([[0.2574888]], dtype=float32),
 array([[0.8506608]], dtype=float32),
 array([[0.5068562]], dtype=float32),
 array([[0.23221181]], dtype=float32),
 array([[0.20508876]], dtype=floa

In [15]:
pred_4_class = []
for pred in predicted_labels :
    if pred < 0.65 :
        pred_4_class.append('no-damage')
    elif pred < 0.75 :
        pred_4_class.append('minor-damage')
    elif pred < 0.85 :
        pred_4_class.append('major-damage')
    else :
        pred_4_class.append('destroyed')

In [16]:
pred_4_class

['no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'minor-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'destroyed',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'destroyed',
 'no-damage',
 'no-damage',
 'no-damage',
 'major-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'destroyed',
 'no-damage',
 'no-damage',
 'no-damage',
 'minor-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'minor-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-dam

In [17]:
actual_labels

['no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'major-damage',
 'major-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'un-classified',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damage',
 'no-damag

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_true = actual_labels, y_pred = pred_4_class))

               precision    recall  f1-score   support

    destroyed       0.00      0.00      0.00         4
 major-damage       0.00      0.00      0.00        16
 minor-damage       0.00      0.00      0.00         3
    no-damage       0.98      0.97      0.97      2542
un-classified       0.00      0.00      0.00        39

     accuracy                           0.94      2604
    macro avg       0.20      0.19      0.19      2604
 weighted avg       0.95      0.94      0.95      2604



/home/abhirag/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
for i in set(pred_4_class):
    print(i, '====', pred_4_class.count(i))

minor-damage ==== 27
no-damage ==== 2515
major-damage ==== 22
destroyed ==== 40


In [20]:
for i in set(actual_labels):
    print(i, '====', actual_labels.count(i))

no-damage ==== 2542
un-classified ==== 39
destroyed ==== 4
major-damage ==== 16
minor-damage ==== 3


In [9]:
data['features']['xy'][0]

{'properties': {'feature_type': 'building',
  'uid': '92abc3b6-4f0d-4520-b6bf-5bf0ae7566ec'},
 'wkt': 'POLYGON ((794.0 469.0,794.0 473.0,795.0 474.0,796.0 474.0,797.0 475.0,803.0 475.0,804.0 474.0,805.0 474.0,805.0 472.0,806.0 471.0,806.0 470.0,805.0 470.0,804.0 469.0,794.0 469.0))'}

In [10]:
max_ious

{'92abc3b6-4f0d-4520-b6bf-5bf0ae7566ec': {'max': 0.4330021367971573,
  'damage': 'no-damage'},
 '2476b5dc-cdee-4335-90f5-ff8790a53f76': {'max': 0.38026472801054817,
  'damage': 'no-damage'},
 '781d4fac-bf5f-4c69-891d-e18aa507a231': {'max': 0.5935944284058069,
  'damage': 'no-damage'},
 '6df9c0a4-acc4-412e-a79a-f1ccbc81787d': {'max': 0.02505655477806296,
  'damage': 'no-damage'},
 '8c8f606c-73fd-4123-9a5f-857427d6ed41': {'max': 0.6518341275948285,
  'damage': 'no-damage'},
 '67630eec-55b2-4d9c-81f0-2cf675eff1cd': {'max': 0.01366721169712525,
  'damage': 'no-damage'},
 'eb3dd7c1-a294-44c9-890b-dfcead2c1bdc': {'max': 0.006140686616366643,
  'damage': 'no-damage'}}